# Generated by Django 3.1.7 on 2021-05-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210505_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormMessage',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
