# Generated by Django 3.1.7 on 2021-05-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210506_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
