# Generated by Django 3.1.7 on 2021-05-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210529_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
