# Generated by Django 3.1.7 on 2021-05-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210510_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
